source-han-sans-*-fonts: exclude fontconfig dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* fixes following errors reported by sstate-diff-machine.sh:
 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86copy and qemuarm ===
ERROR: source-han-sans-cn-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-cn-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-cn-fonts_1.004.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-cn-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-cn-fonts_1.004.bb.do_packagedata']
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash e7fb65be80d659ad30e73c7bad692456
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 96542b26ecfbce93b84889ee4a2e4746
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from e7fb65be80d659ad30e73c7bad692456 to 96542b26ecfbce93b84889ee4a2e4746

ERROR: source-han-sans-jp-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-jp-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-jp-fonts_1.004.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-jp-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-jp-fonts_1.004.bb.do_packagedata']
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash e7fb65be80d659ad30e73c7bad692456
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 96542b26ecfbce93b84889ee4a2e4746
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from e7fb65be80d659ad30e73c7bad692456 to 96542b26ecfbce93b84889ee4a2e4746

ERROR: source-han-sans-kr-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-kr-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-kr-fonts_1.004.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-kr-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-kr-fonts_1.004.bb.do_packagedata']
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash e7fb65be80d659ad30e73c7bad692456
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 96542b26ecfbce93b84889ee4a2e4746
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from e7fb65be80d659ad30e73c7bad692456 to 96542b26ecfbce93b84889ee4a2e4746

ERROR: source-han-sans-tw-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-tw-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-tw-fonts_1.004.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.5.bb.do_populate_sysroot:virtual:native', 'ttf-fontssource-han-sans-tw-fonts_1.004.bb.do_package', 'ttf-fontssource-han-sans-tw-fonts_1.004.bb.do_packagedata']
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash e7fb65be80d659ad30e73c7bad692456
 changed to
/home/jenkins/oe/world/shr-core/openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 96542b26ecfbce93b84889ee4a2e4746
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from e7fb65be80d659ad30e73c7bad692456 to 96542b26ecfbce93b84889ee4a2e4746

ERROR: 4 errors found in /home/jenkins/oe/world/shr-core/tmp-glibc/sstate-diff/1456139140/signatures.qemuarm.do_package_write_ipk.sigdata.log
ERROR: 4 issues were found in these recipes: source-han-sans-cn-fonts source-han-sans-jp-fonts source-han-sans-kr-fonts source-han-sans-tw-fonts

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>